### ISSUE TITLE
Crashing Upon Entering The Nether

### ISSUE THREAD

**Issue by TheStxche** [lucaargolo/fabric-seasons#105] opened 2023-04-17 06:58 UTC
I am using the curseforge modpack Fantasy Minecraft. I have added 4 mods to my third party server. Those mods are: extended storage, open parties and claims, the create mod that allows create and open parties to work, and on just server side I installed chunky. I have been getting a crash whenever I enter the nether. The modpack has BetternetherX on it. Whenever I enter the nether I have shaders on but even with them off the same thing happens.

This is the crash report I got when I initially started experiencing this: https://mcpaste.io/7946109ef0fd7c23

This is the most recent crash report: https://mcpaste.io/595e47253a9caa75

I have sent in a bug report to the devs of Fantasy Minecraft and I sent them the first crash report linked above, they concluded that it was Fabric Seasons that was causing the crash. I asked what they recommend and they sent me to you. So if you have any insight as to how I can fix this problem it would be much appreciated!

**Comment by lucaargolo** [comment] 2023-04-21 00:37
Heyy, since this is a watchdog crash, as I said in Discord, it most likely isn't being caused by another mod. Also, this mod doesn't even work in the nether by default (except if you enabled it in the config). 

Considering that the mod also doesn't appear in the second crash and that I couldn't reproduce it, I'll be closing this issue for now. 

If this crash still happens with version 2.0 of the mod, and it consistently shows up on the report, feel free to reopen it.

**Closed as completed by lucaargolo** 2023-04-21 00:37 UTC
