### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Romz24** [lucaargolo/fabric-seasons#49] opened 2021-10-01 23:44 UTC
I am using your mod for seasons and mod for VoxelMap. From time to time, when opening a card, my game crashes. If you turn off the mod for the seasons, I did not notice this problem.

Game version: **1.16.5**
Fabric Seasons: **1.2-BETA**
VoxelMap: **1.10.15**
Fabric API: **0.40.1**
Fabric Loader: **0.11.7**

Crash log: [crash-2021-10-02_02.39.34-client.txt](https://github.com/lucaargolo/fabric-seasons/files/7270578/crash-2021-10-02_02.39.34-client.txt)

**Comment by Romz24** [comment] 2021-10-04 01:41
I caught another crash just when I log into the game.

File: [crash-2021-10-04_04.37.00-client.txt](https://github.com/lucaargolo/fabric-seasons/files/7274977/crash-2021-10-04_04.37.00-client.txt)

**Comment by samb96** [comment] 2021-12-02 17:00
I've also had a crash in the `injectBiomeTemperature` method that I think might be related. I am also using VoxelMap among other mods.

Game version: **1.17.1**
Fabric Seasons: **1.3.1-BETA**
VoxelMap: **1.10.15**
Fabric API: **0.42.1**
Fabric Loader: **0.12.5**

[crash-2021-12-02_10.36.31-client.txt](https://github.com/lucaargolo/fabric-seasons/files/7643736/crash-2021-12-02_10.36.31-client.txt)

**Comment by samb96** [comment] 2021-12-02 17:26
This crash is happening to me consistently at the moment.

some notes:

- it is night time with 16 days left until spring
- the crash usually seems to happen when I'm about to go to bed but sometimes it's just before I'm about to right click the bed (probably a coincidence)
- the server is fine and is reporting no errors
- it only started happening today, the last thing I did last night was setting up and moving all my items to an applied energistics 2 ME system

**Comment by samb96** [comment] 2021-12-02 20:26
I did some more experimentation and I don't think the root cause of my crash is because of this mod. My client still crashes even with the mod disabled. Sorry for the irrelevant report~

**Comment by lucaargolo** [comment] 2023-04-21 00:41
Closing this since I was never able to properly reproduce it and the mod code changed a lot since it was reported.

**Closed as completed by lucaargolo** 2023-04-21 00:41 UTC
