### ISSUE TITLE
game crash on exploring aether

### ISSUE THREAD

**Issue by kajdaniec** [lucaargolo/fabric-seasons#62] opened 2021-12-27 10:14 UTC
as in title exploring aether after some time crashes game. attaching crash report to analyze
[crash-2021-12-27_11.09.00-client.txt](https://github.com/lucaargolo/fabric-seasons/files/7779697/crash-2021-12-27_11.09.00-client.txt)
.

**Comment by MSandro** [comment] 2021-12-27 10:39
might be similar to #49

**Comment by MSandro** [comment] 2021-12-27 11:31
![image](https://user-images.githubusercontent.com/10937159/147467754-8c4cdcd4-71b4-4ff9-9e23-c5ea7e18ad06.png)
Biome Shading should be disabled, so it will not crash anymore.

**Comment by lucaargolo** [comment] 2023-04-21 00:41
Closing this since I was never able to properly reproduce it and the mod code changed a lot since it was reported.

**Closed as completed by lucaargolo** 2023-04-21 00:41 UTC
