### ISSUE TITLE
Quilt Compatibility

### ISSUE THREAD

**Issue by rockrevenchy** [lucaargolo/fabric-seasons#76] opened 2022-06-30 19:39 UTC
I was wondering if there was plans to migrate towards or allow the use of quilt with this mod

as it stands, it refuses to launch under quilt because it doesnt recognizes it as an acceptable dependency 

```
Dependency for mod 'seasons' on fabricloader versions [>=0.14.8] (0 valid options, 1 invalid options)
	x provided mod 'fabricloader' version '0.14.7' from mod 'quilt_loader' version 0.17.1-beta.4 loaded
```

Btw thx for making this mod, truly adds life to a minecraft world with another mod such as snow real magic ;p

https://quiltmc.org/

**Comment by rockrevenchy** [comment] 2022-06-30 20:05
I removed the dependencies in fabric.mod.json and forced it to load on quilt 1.19 as an experiment.
it seems to work flawlessly so far  

"depends": {
    "minecraft": "1.19.x"
  }

**Comment by lucaargolo** [comment] 2022-06-30 20:16
The mod should work fine on Quilt as long as they keep support for fabric mods. I'll take a look at how to handle the dependencies later.

**Comment by gdude2002** [comment] 2022-07-07 22:31
This issue is caused by Quilt Loader being a little behind. However, it should already be fixed in Quilt Loader 0.17.1-beta.6 - can you make sure you're using that and try again?

**Comment by rockrevenchy** [comment] 2022-07-08 04:58
Oh sorry, yeah I'll do that tomorrow and come back to you

**Comment by rockrevenchy** [comment] 2022-07-08 23:55
I was on quilt 0.17.1 beta.4 when the issue was happening

as of beta.6 it works without requiring any edit!

Thanks for your assistance :)

**Closed as completed** 2023-04-22 00:23 UTC
Labels: bug, enhancement
