### ISSUE TITLE
All blocks stop rendering when season changes.

### ISSUE THREAD

**Issue by Bobily8** [lucaargolo/fabric-seasons#24] opened 2021-05-12 11:14 UTC
When the season changes naturally or through the use of commands (either skip season or adding time) all blocks cease rendering. Only entities and particles render. For some reason going through an immersive portal fixes the issue but it breaks again if you relog. Setting the time to 0 also fixes the issue (even when relogging) but only whilst in spring. We have tried fiddling around with render distances/different areas of the world including different accounts and different computers and keep experiencing the issue.

![2021-05-12_12 13 44](https://user-images.githubusercontent.com/84076816/117966201-8d3ce800-b31b-11eb-8da2-e69309f039d9.png)

**Comment by lucaargolo** [comment] 2021-05-13 13:06
https://user-images.githubusercontent.com/49497195/118129462-93da6680-b3d2-11eb-9747-0f28d70bad23.mp4

This is for sure caused by something else, maybe a mod incompatibility. I don't even mess with rendering, and as you can see in my video, everything is working fine.

**Comment by MitztheKat** [comment] 2021-05-15 12:57
> When the season changes naturally or through the use of commands (either skip season or adding time) all blocks cease rendering. Only entities and particles render. For some reason going through an immersive portal fixes the issue but it breaks again if you relog. Setting the time to 0 also fixes the issue (even when relogging) but only whilst in spring. We have tried fiddling around with render distances/different areas of the world including different accounts and different computers and keep experiencing the issue.
> 
> ![2021-05-12_12 13 44](https://user-images.githubusercontent.com/84076816/117966201-8d3ce800-b31b-11eb-8da2-e69309f039d9.png)

Yo, I think he could assist if you provided logs.

**Comment by Jakaya0897** [comment] 2021-05-19 13:49
I can't help but notice lucaargolo In your demonstration it says Active renderer Indigo Renderer

I'm also experiencing this crippling bug while I'm not sure what logs I can provide as it's not crashing and there are no errors or even mentions to seasons in the log. 

I do use sodium and companion performance related mods as well as immersive portals I believe this may be the cause of the issue.

With Seasons:
No Weather: 400 FPS 
With Weather: 0 FPS

Without Seasons 
No Weather: 400 FPS 
With Weather: 372  FPS

http://prntscr.com/134d2lc

Sodium-fabric-mc1.16.4-0.1.1-ipc2
Immersive-portals-0.90-mc1.16.5-fabric

I have tested once seasons is removed this behaviour seems to go away, so I'm assuming it's some relationship between your mod and sodium the issue with this is my FPS count will take priority over seasons but id love to have both I'm greedy like that ;)

**Comment by OarisHunter** [comment] 2021-06-05 21:09
I have the same issue. While this might also be caused by sodium, immersive portals is the culprit for me.

**Comment by MorganRO8** [comment] 2021-06-27 21:47
If you set your render distance down to 2-3 chunks you should be able to move around, at least that's how it worked for me. After that I did time set 0 and it reset the seasons and completely fixed the issue. This happened on a server for me so me and a few friends experienced it. I'm not 100% sure but I think it might have something to do with resource packs? I'm gonna keep looking but any help on this would be much appreciated.

**Comment by MorganRO8** [comment] 2021-07-01 18:23
I ended up figuring out what I think to be the issue, and @OarisHunter seems to be right it is an issue between seasons and immersive portals. I created an issue on the immersive portals github and they looked into it. Apparently it's cause by the fact that with immersive portals you're loading multiple worlds, that have different seasons apparently, which causes a loop of reloading the renderer. Here's the other issue, it may contain more info than I've summarized https://github.com/qouteall/ImmersivePortalsMod/issues/757
I feel like this should be fixable though, which is sweet!

edit: quote from the original post that seemed relevant "This can only be fixed by Seasons. Seasons can only track the season for the overworld dimension, or track different season data for different dimensions. You can open an issue to Seasons."

**Comment by TheSpiderDungeon** [comment] 2021-09-04 22:14
Encountering the same issue, I also have this mod and Immersive Portals installed (with dimension stack active). A fix would be nice so I can play on my world again.

**Comment by SalvieMundi** [comment] 2021-09-08 00:41
Any ideas when a fix might be coming for this?

**Comment by lucaargolo** [comment] 2021-09-30 16:54
This issue should be fixed on the 1.3-BETA release.

**Closed by lucaargolo** 2021-09-30 16:54 UTC
Labels: mod incompatibility
