### ISSUE TITLE
Breaking/Changing world generation in 1.18 

### ISSUE THREAD

**Issue by MazeVI** [lucaargolo/fabric-seasons#59] opened 2021-12-18 22:36 UTC
From what I've tried, it seems the mod is messing with the world generation on 1.18, as in some biomes that should have a much lower height end up generating in heights where only biomes such as jagged_peaks and windswept biomes would generate. I've seen the old_taiga_growth biome nestled in with a jagged-peaks biome because it was so high, that the jagged_peaks biome looked like a weird snow patch inside the forest biome.
In other situations, some biomes would generate so high it would look like an Amplified-like world gen.
I am writing this based on the latest BETA release version, so I hope this helps.
I have not taken any screenshots yet because I've only found this issue now.
The issue doesn't seem to affect cave generation, only surface biome generation.

**Comment by lucaargolo** [comment] 2023-04-21 00:15
Heyy, I'm closing this since I wasn't able to reproduce it. I tried comparing worlds generated in vanilla and with the seasons mod using the same seed and it looked identical to me. If this somehow is still happening in version 2.0 of the mod, feel free to reopen this issue.

**Closed as completed by lucaargolo** 2023-04-21 00:15 UTC
