### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by jarocajavi** [lucaargolo/fabric-seasons#84] opened 2022-09-12 19:58 UTC
Hello, i open a ticket in Supplementaries page, but i think must be here.
https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/449

My second crash was be with "mangle_seed" and is the reason i am here, see the pattern, 2 different seeds and same crash.
https://bytebin.lucko.me/37eKMVae7B

Thanks anyway i hope this can be helpfull

**Comment by XOX-CH** [comment] 2022-09-16 04:11
I'm getting the error Crash: Player Entity. I crashed when changing the time with the command: /time set 19500000d. My saves are therefore inaccessible Delete MOD Crash: Player Entity -

**Comment by jarocajavi** [comment] 2022-09-16 12:01
Sorry, what?

**Comment by lucaargolo** [comment] 2023-04-20 23:56
Closing this since I was never able to properly reproduce it and the mod code changed a lot since it was reported.

**Closed as completed by lucaargolo** 2023-04-20 23:56 UTC
