### ISSUE TITLE
tesselating block in-world

### ISSUE THREAD

**Issue by LordDecay26** [lucaargolo/fabric-seasons#53] opened 2021-11-21 17:30 UTC
on the latest version for 1.17, game crashed as it changed seasons
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 11/21/21, 12:28 PM
Description: Tesselating block in world - Indigo Renderer

java.lang.NullPointerException: Cannot invoke "java.util.Optional.orElseGet(java.util.function.Supplier)" because the return value of "net.minecraft.class_1959.redirect$dmj000$getSeasonGrassColor(net.minecraft.class_4763)" is null
	at net.minecraft.class_1959.method_8711(class_1959.java:407)
	at net.minecraft.class_638.method_23780(class_638.java:707)
	at net.minecraft.class_638.method_23781(class_638.java:689)
	at net.minecraft.class_4700.method_23770(class_4700.java:44)
	at net.minecraft.class_638.method_23752(class_638.java:689)
	at net.minecraft.class_853.method_23752(class_853.java:135)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4962(class_1163.java:18)
	at net.minecraft.class_324.method_1693(class_324.java:48)
	at net.minecraft.class_324.method_1697(class_324.java:112)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderInfo.blockColor(BlockRenderInfo.java:83)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.colorizeQuad(AbstractQuadRenderer.java:73)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.tesselateSmooth(AbstractQuadRenderer.java:119)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:135)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:97)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:60)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)
	at net.minecraft.class_846$class_851$class_4578.redirect$zbe000$hookChunkBuildTesselate(class_846.java:723)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:524)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:447)
	at net.minecraft.class_846.method_22757(class_846.java:132)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1806)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1959.method_8711(class_1959.java:407)
	at net.minecraft.class_638.method_23780(class_638.java:707)
	at net.minecraft.class_638.method_23781(class_638.java:689)
	at net.minecraft.class_4700.method_23770(class_4700.java:44)
	at net.minecraft.class_638.method_23752(class_638.java:689)
	at net.minecraft.class_853.method_23752(class_853.java:135)
	at net.minecraft.class_1163.method_4965(class_1163.java:14)
	at net.minecraft.class_1163.method_4962(class_1163.java:18)
	at net.minecraft.class_324.method_1693(class_324.java:48)
	at net.minecraft.class_324.method_1697(class_324.java:112)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderInfo.blockColor(BlockRenderInfo.java:83)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.colorizeQuad(AbstractQuadRenderer.java:73)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractQuadRenderer.tesselateSmooth(AbstractQuadRenderer.java:119)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.renderQuad(TerrainFallbackConsumer.java:135)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:97)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainFallbackConsumer.accept(TerrainFallbackConsumer.java:60)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)

-- Block being tesselated --
Details:
	Block: Block{minecraft:grass_block}[snowy=false]
	Block location: World: (-122,66,-624), Section: (at 6,2,0 in -8,4,-39; chunk contains blocks -128,-64,-624 to -113,319,-609), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tesselateBlock(TerrainRenderContext.java:105)

-- Affected level --
Details:
	All players: 1 total; [class_746['GandalfTheDanke'/33, l='ClientLevel', x=124.59, y=63.00, z=-406.05]]
	Chunk stats: 2809, 2277
	Level dimension: minecraft:overworld
	Level spawn location: World: (138,63,-128), Section: (at 10,15,0 in 8,3,-8; chunk contains blocks 128,-64,-128 to 143,319,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 514731 game time, 418758 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_846.method_22755(class_846.java:136)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1806)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1106733296 bytes (1055 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7155
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 53055.80
	Virtual memory used (MB): 42352.28
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 554.43
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		adaptivebrightness: Adaptive Brightness 1.0.2
		additionaladditions: Additional Additions 2.2.0
		advancedcompass: Advanced Compass 1.2.6
		advancementplaques: Advancement Plaques 1.4.2
		adventurez: AdventureZ 1.4.2
		alloy_forgery: Alloy Forgery 2.0.6
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		annotateddi: Annotated DI 2.0.3+1.17.1
		anthropophagy: Anthropophagy 1.17-4
		antiqueatlas: Antique Atlas 6.1.1-fabric-mc1.17.1
		aopalliance_aopalliance: aopalliance 1.0
		apoli: Apoli 2.0.5
		apugli: Apugli 1.1.6
		aqupdcaracal: Caracal mob 1.17-1.3.2
		architectury: Architectury 2.6.35
		artofalchemy: Art of Alchemy: Memoriam 1.2.0+1.17.1
		automatone: Automatone 0.4.1
		awesomedungeon: Awesome Dungeon 1.1.2
		axesareweapons: Axes Are Weapons 1.5.1
		barrenisles: Barren Isles 1.0.7
		besmirchment: Besmirchment 1.17.1-6
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bewitchment: Bewitchment 1.17-14
		black-powder: Black Powder 1.0.6
		blame: Blame 1.17.1-4.3.1-fabric
		blast: BLAST 1.8.1
		bountiful: Bountiful 1.0.0
		calio: Calio 1.3.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		chalk: Chalk 1.0.2
		charmonium: Charmonium 3.3.0
		charter: Charter 0.1.0
		chat_plus: Chat+ 2.1.5
		chime: Chime 1.2.0-SNAPSHOT
		chipped: Chipped 1.1.1
		chord: Chord 1.8.0+1.17-rc1-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 7.0.10
		collective-fabric: Collective (Fabric) 1.62
		com_alexdupre_pngj: pngj 2.1.2.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_flowpowered_flow-math: flow-math 1.0.3
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		com_google_inject_guice: guice 5.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		companion_bats: Companion Bats 1.18.4
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		conjuring: Conjuring 1.0.15
		cosmetica: Cosmetica 0.2.1
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customstars: Custom Stars 0.7+1.17
		damagetint: Damage tint 1.1.0
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dark-loading-screen: Dark Loading Screen 1.6.11
		darkness: True Darkness 1.6.74
		darkpaintings: Dark Paintings 4.0.2
		darkrites: Dark Rites 1.17.1-1
		darkwaters: Dark Waters 0.0.9
		deathcoords: Death Coords 1.0.0
		defaultsettings: DefaultSettings 3.1.0
		dimdoors: DimensionalDoors 4.0.0+beta.3-27.10.2021
		dracomelette: Dracomelette 1.17-2
		dragonloot: DragonLoot 1.0.9
		drinkbeer: Drink Beer 2.3
		dynamicfps: Dynamic FPS 2.0.6
		dynmus: Dynamic Music 1.3.1
		eldritch_mobs: Eldritch Mobs 1.9.6
		enchantment_lore: EnchantmentLore 1.2.1+MC1.17.1
		enchantment_potions: Enchantment Potions 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enderscape: Enderscape 0.1.2
		enhancedcelestials: Enhanced Celestials 2.0.5
		exaltation: Exaltation 0.1.10
		extra: Extra classes 1.0.0
		extraorigins: Extra Origins 1.17-10
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-tpa: FabricTPA 3.0.1
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabrichomes: FabricHomes 2.0.0
		fabricloader: Fabric Loader 0.11.7
		fabricwarps: FabricWarps 2.0.0
		fabulousclouds: Fabulous Clouds 0.2.3
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingattack: Falling Attack 1.17.1-1.1.2
		fallingleaves: Falling Leaves 1.7.4+1.17.1
		fancymenu: FancyMenu 2.3.7
		fantasy: Fantasy 0.4.2+1.17
		farmersdelight: Farmer's Delight 1.17.1-0.1.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.1
		fireplacelib: Fireplace Lib 6.0.7+1.17.1
		flan: Flan 1.17.1-1.6.3
		flonters: Flonters 1.2.1+1.17.1
		flycommand: FlyCommandMod 1.17.1-1.2
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.2
		geckolib3: Geckolib 3.0.27
		geodes: More Geodes 1.1.1
		grandeconomy: Grand Economy 5.1.0+1.17.1
		graveyard: The Graveyard 2.1
		grindstonesharpertools-fabric: Grindstone Sharper Tools (Fabric) 1.6
		guardiansgalore: GuardiansGalore 1.17.1-2.1
		haema: Haema 1.7.7+1.17
		harmfulstonecutters: Harmful Stonecutters 1.0.2
		healingcampfire-fabric: Healing Campfire (Fabric) 3.3
		healthoverlay: Health Overlay 4.0.2
		hologram-api: Hologram API 0.2.0+1.17.1
		holograms: Holograms 1.3.0+1.17.1
		homecamp: Home Camp 2.2.0+1.17.1
		horsestonks: Horse Stonks 1.0.0
		hwg: Happiness is a Warm Gun 1.0.27
		iceberg: Iceberg 1.0.23
		illuminations: Illuminations 1.10
		image2map: Image2Map 0.2.1
		imggen: Image World Generator 1.3.3
		impersonate: Impersonate 2.3.5
		inmis: Inmis 2.3.2-1.17.1
		inventoryhud: Inventory HUD + 3.4.1
		invview: InvView 1.4.6-1.17.1+
		itemborders: Item Borders 1.1.4
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		javax_inject_javax_inject: javax.inject 1
		kambrik: Kambrik 1.1.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kits: Kits 1.4.0-mc1.17.1
		konkrete: Konkrete 1.3.0
		lakeside: Lakeside 1.1.0+1.17
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.1+1.17.1
		libninepatch: LibNinePatch 1.1.0
		locki: Locki 0.5.1
		lovely_snails: Lovely Snails 1.0.3+1.17
		matrix: Matrix 1.0.0
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.17.1
		multi_item_lib: Multi Item Lib 1.4.0
		multiworld: Multiworld-Fabric 1.1
		mypack: My Pack 1.0.0
		mysql_mysql-connector-java: mysql-connector-java 8.0.25
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nibbles: Nibbles 1.1.0
		npcvariety: NPC Variety 2.2.0
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.36.0
		origins: Origins 1.1.4
		origins-classes: Origins: Classes 1.2.2
		ostoverhaul: Ost Overhaul 0.1
		owo: oωo 0.3.2+1.17
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17.1-57-FABRIC
		pehkui: Pehkui 2.5.3+1.14.4-1.18
		perorate: Perorate 1.2.1
		placeholder-api: Placeholder API 1.1.1+1.17.1
		playerabilitylib: Pal 1.4.0
		polymorph: Polymorph 0.0.14-1.17.1
		ppp: Port's Parrots Plus 1.3.0
		puddles: Puddles 1.2.0
		quickspyglasser: Quick Spyglasser 0.3.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		realisticfirespread: Realistic Fire Spread 1.17-3
		recipeconditions: Fabric Recipe Conditions 0.4.0
		requiem: Requiem 2.0.0-beta.1
		requiem-core: Requiem-Core 2.0.0-beta.1
		requiemapi: Requiem-API 2.0.0-beta.1
		respawnablepets: Respawnable Pets 1.17-5
		rightclickharvest: Right Click Harvest 1.5.0
		ripplers: Ripplers 0.3.1
		riverredux: River Redux 0.2.0
		rocks: This Rocks! 1.5.1
		roughlyenoughitems: Roughly Enough Items 6.1.329
		rpgstats: RPGStats 4.2.2+1.17.1
		ruined_equipment: Ruined Equipment 1.3.0
		satin: Satin 1.6.4
		sbm-jukebox: SBM-Jukebox 1.0.0
		scorch: Scorch 1.2.0
		seamless_loading_screen: Seamless Loading Screen 1.3.6+1.17.1
		seasons: Fabric Seasons 1.3.1-BETA+1.17
		secondchance: Second Chance 1.2.0
		seedy-behavior: Seedy Behavior 1.0.2+1.17.1
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shadeorigin: A Shadekin Origin 2.0
		sihywtcamd: sihywtcamd 1.5.2+1.17.1
		skylorlib: SkyLib 1.0.5
		slimyfloor: Slimy Floor 1.17.1-1.2.0
		smoothswapping: Smooth Swapping 0.4.2
		snowpig: Snow Pig 1.2.0
		snowundertrees: Snow Under Trees 1.0.0
		somnus: Somnus API 0.0.14-1.17.1
		spellbound: Spellbound 1.6.0
		squirrels: Squirrels 1.2.0-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		statues: Statues 1.0.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		strawgolem: Strawgolem 1.10-B2
		sulfurpotassiummod: Sulfur & Potassium 1.1.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 1.6.1
		theplaneswalker: Origins: The Planeswalker unspecified
		toomanyorigins: TooManyOrigins 0.2.3
		trade: Trade 1.2.1
		transportables: Transportables 1.0.6
		traverse: Traverse 4.0.0
		trinkets: Trinkets 3.0.4
		twigs: Twigs 1.0.2
		vanilla_degus: Vanilla Degus 1.2.3
		vistas: Vistas 1.4.4
		visuality: Visuality 0.3.0
		waystones: Waystones 2.2.1
		what: WHAT 1.0.0
		window_title_changer: Window Title Changer 2.1.1-1.17
		woods_and_mires: Woods and Mires 1.1.1+1.17
		wthit: wthit 3.11.2
		xps: Xp Obelisk 0.2.2.r_for_1.17.x_Fabric
		yungsapi: YUNG's API 1.17-Fabric-19
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ERR
	Window size: 2560x1377
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, charmonium/journeyman
	Current Language: English (US)
	CPU: 20x Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
	Player Count: 1 / 8; [class_3222['GandalfTheDanke'/33, l='ServerLevel[Actually going to try to play]', x=124.59, y=63.00, z=-406.05]]
	Data Packs: vanilla, dimdoors/default, dimdoors/classic, Fabric Mods

**Comment by lucaargolo** [comment] 2023-04-20 23:51
Closing this since I was never able to properly reproduce it and the mod code changed a lot since it was reported.

**Closed as completed by lucaargolo** 2023-04-20 23:51 UTC
