### ISSUE TITLE
Falling snow on water generates ice with snow layer on top.

### ISSUE THREAD

**Issue by Cha0sPudd1ng** [lucaargolo/fabric-seasons#97] opened 2023-01-21 11:07 UTC
![2023-01-21_11 58 53](https://user-images.githubusercontent.com/1367047/213864149-51862f54-f33c-4f63-9010-5d7a2705fc23.png)

Fabric 1.19.2 (0.14.12)
fabric-seasons-1.4-BETA+1.19

**Comment by lucaargolo** [comment] 2023-04-21 00:12
Heyy, this mod doesn't change snow/ice behavior, it just enables it during the winter season. This is probably being caused by another mod. Also as of version 2.0, the mod doesn't add any new blocks, it just injects its melting logic into the vanilla ones, so if this was somehow being caused by this mod it got fixed in the newest update.

**Closed as completed by lucaargolo** 2023-04-21 00:12 UTC
